<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableComHosting>false</EnableComHosting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Copyright>Copyright (C) 2025-2026 Jack Studio, Inc.</Copyright>
    <Authors>Jack Software Engineer</Authors>
    <Company>Jack Studio</Company>
    <Title>Jack Software Engineer</Title>
    <PackageReleaseNotes>Windows Firewall Management</PackageReleaseNotes>
    <Description>Windows Firewall Management</Description>
    <ApplicationIcon>firewall.ico</ApplicationIcon>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <Version>2.0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
    <IsPublishable>True</IsPublishable>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
    <IsPublishable>True</IsPublishable>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="NETCONLib">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>43e734ca-043d-4a70-9a2c-a8f254063d91</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="NetFwTypeLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>58fbcf7c-e7a9-467c-80b3-fc65e8fcca08</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="firewall.ico" />
  </ItemGroup>



</Project>